server :
  port : 8080
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/posworld?serverTimezone=UTC&amp&characterEncoding=UTF-8
    username: root
    password: 1234


