
server:
  port : 8001
spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url:  jdbc:mysql://localhost:3306/posworld?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB


file: C:\Users\klove\Documents\Spring_POSWORLD\posworld\src\main\resources\static


mybatis:
  config-location: classpath:config/myBatis.xml

jwt :
  secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
  expTime: 3600000



