server:
  port : 8001
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url:  jdbc:mysql://localhost:3306/posworld?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  config-location: classpath:config/myBatis.xml

jwt:
  secret_key: "secret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_key"
  expTime: 86400000





