server:
  port : 8001
spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url:  jdbc:mysql://localhost:3306/posworld?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

file: C:\Users\user\posworld\Spring_POSWORLD\Spring_POSWORLD\posworld\src\main\resources\static

mybatis:
  config-location: classpath:config/myBatis.xml

jwt:
  secret_key: "secret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_key"
  expTime: 86400000







